hash-format = "sha256"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "2d3cbf3d77196a08a014270238740515c1b634bc11ad83a51140d7bcfc62d6b3"
metafile = true

[[files]]
file = "mods/almanac.pw.toml"
hash = "49a33ac37445e3c08eb1a958b4f81f0c9ce356a8c08ace17e5df98e18558b4b1"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "ddc96b08f1a32a08edd9b8e34257b9a37ea9b3836ae4371e26f54c4ade4fe3f1"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1502d3ac2c2ce4d3dc4c2db6ca6e95fb2a5d4a279e6e1413f6c427be222887a0"
metafile = true

[[files]]
file = "mods/armor-stand-arms.pw.toml"
hash = "51ca4a5cca10cef8a6ed1e12accd6f6a9b4c3331715de01fc47419dc22dd980e"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "f8805d3902fb3e31ea9e53f684e3d731b5ac7d2fd2507c475fd1f5f4da266a2f"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "f34fa12fe7701cf0776fef1a1f1e2e3c7227f53302b3d87b7ff307f0446a68d2"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
hash = "94c3fc74cf184c9e5c597609dde733137f823bed718fcce32cdefaa040aa9977"
metafile = true

[[files]]
file = "mods/block-runner.pw.toml"
hash = "d7a32c408b45a277d7f13a1eeed2013a5b6f63645b7fbeb523f7ca93c0dd4682"
metafile = true

[[files]]
file = "mods/bluemap.pw.toml"
hash = "24737d4ec343e590df0fb597f52bd792557300b659b828492bfd51d63c1fe52d"
metafile = true

[[files]]
file = "mods/bookshelf-inspector.pw.toml"
hash = "9d984d80916c370027dec03b1422e7280ed5c4ba79fb471288e272d169d95b64"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "4ee1808a7fb319d469dece5752cedb05dacb9afbe48021fa664f54b8c83fdc45"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "6083db761c82eece49adba0b0cee0b37068422e2eb170b7039ebae65972d03e1"
metafile = true

[[files]]
file = "mods/cherished-worlds.pw.toml"
hash = "9d07c9ba99c427bc750413e68552dcb497c6aec4f2483bf4a46bd93a19e886a3"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "64badefe03082699f587274a31d1f0793583a4d88aac8ea2226162f80783fb52"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "717d8ac591dba59be4767a179e1359747561e54ccfcac42161fd6bf54339a78b"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "b98e0aca52ce8d08ee8df7177886589511b8bca779af078a6ff4837e814bccf4"
metafile = true

[[files]]
file = "mods/cobweb.pw.toml"
hash = "78c5c7a98ee86b97042c6ccc82d923a0f7d068da094ef3e687666cffc7415a57"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "b152c75412428e5f53667cb0836fa1323ca93cbd925e456239710a2e261d9963"
metafile = true

[[files]]
file = "mods/crate-delight.pw.toml"
hash = "4aec48b176bf12adbbae1c55152db40a46ba59a8f746b44f60f3d681cbb19258"
metafile = true

[[files]]
file = "mods/crops-love-rain.pw.toml"
hash = "f80771c373ac5f054b7c7e198c680cd7fff0fcc40d5753517b4b0acefa1c5729"
metafile = true

[[files]]
file = "mods/detail-armor-bar-reconstructed.pw.toml"
hash = "4a4d1e1b5afdc1cf7f810321315e26662ff92b0c10abf85203174773d6075e14"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "064f49cf069fedf5bdcb16e0bce408ce78032d9c40d60e5164cc1f9c54576e5d"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
hash = "e9c66a831545c31e1bd5f898974222a7e04e548018dda0a4db0da7c6997c8017"
metafile = true

[[files]]
file = "mods/easy-shulker-boxes.pw.toml"
hash = "0e3945d880e497398559c2a6419f83d2b76cd799b70db993089f27c32408b3a0"
metafile = true

[[files]]
file = "mods/elytra-trims.pw.toml"
hash = "25169fc931b59ac271a5f3aca9e3c7e43ee2f5c91f66cb04f5107df7f5142b1d"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "f234a39f70e9a92f27cb5462616a1f8a78673804380c06d84e7c4ea5fa06e367"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "b6dd8c2e3c0b386b2551844c81c41940554f373c24aa8a35f20dfd63022e59fb"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "6d74eac8e7c0d542a37681dc808a1af1213fd91b5a9361cca1274d7426bb278e"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "0345fbfa8542b5ec84535fe2aff0f5cc4e801ecc337f926d4e2310b53f458569"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "16475920a19745939858440691992a38e7244c712d5e607695f6dca394622c40"
metafile = true

[[files]]
file = "mods/fast-item-frames.pw.toml"
hash = "e19aa2d83e60f302ad9145e4e1246916d2036541def8b7076024b9073fcd7587"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "186a261ded1911abf559dce21b22eadc1e96de7767982e58f458b82a89a924ba"
metafile = true

[[files]]
file = "mods/flashback.pw.toml"
hash = "e56ab572b86cd0f11f62baa45556a21cf767197a6f028d967814166b10ed3784"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "d74f72f3bf13c4ef7d60b6e2defecd3c7af77ed9be7764cf1ed10ea1fd707a1f"
metafile = true

[[files]]
file = "mods/forgiving-void.pw.toml"
hash = "1ade8db276ce95be00dc38117b707a6c26eb3056922bced4056a93b4e8dfde7d"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "169d919fbd981172a518ac0e3667dbf7f987611c3147b06ec3412d63bac553b2"
metafile = true

[[files]]
file = "mods/harvest-with-ease.pw.toml"
hash = "bf50e23afa9be355eb5d95a1d32fe196411f77632405ecf8e4f70e9a1266408e"
metafile = true

[[files]]
file = "mods/horse-expert.pw.toml"
hash = "5420daa16e2dcb0c234c35aeeca15e20ac4f628a316829774c7a02166a33f412"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "77364cc74f5c0819ef77e5e2fd11bd304ad98dc193348d3d875e23fae62f8f74"
metafile = true

[[files]]
file = "mods/inventory-sorting.pw.toml"
hash = "3ab06d3b51894cb9098c9bcb1206f8ccf49d8cd259a3ad6fa219fe2079fca824"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "a077e0482f50add9ef20e962a7939aa678583cb3f354fb6b6124219badafdd4d"
metafile = true

[[files]]
file = "mods/just-hammers.pw.toml"
hash = "6961b9b320387c2449f2ac9a297e2843de7fde9a8200bf57c45af32f5b65ce6b"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "8f6e0157b42ba668c0ba9aa7eff94b3b91a8f58bcd357e574d70a7b160d4337c"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
hash = "8c75e0407d200803b12333bc2dc59f25b3e0060aa3f07ccfa59ebaa194acd560"
metafile = true

[[files]]
file = "mods/lighty.pw.toml"
hash = "eebcb6dd93f1d09f39bf699c11f213cab1d0f8f3c248cbe8b79659633759a051"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "84957275e9dc6f07f4244ce3303536e3d73b0e72eb1696ccd024168a52c29c98"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "ffd2bde70110ba1d26bf841930556307a5bdfa3159b194e6e30ac5192be61754"
metafile = true

[[files]]
file = "mods/ly-graves.pw.toml"
hash = "719610a44c7d14c004864a93c0f580383ed95e71d8a563c98464d4ec3822d186"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "bda12a83dc36c4a8e5b45438700b54bf21c182d923f7f8255570893628281e06"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "5dd45d5fd5e1ae2bd521b93a70b83c69b57ada18f424c6562d8c6ea9980cfb3e"
metafile = true

[[files]]
file = "mods/more-delight.pw.toml"
hash = "77c6a261e282d638b4f51985125bc8ed618e32790a119e0a13d2ba8743d5c2e6"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "204a4b3b041fad4bb4dc543c74d540fcf239710494d2130cebe700bf1d8a7805"
metafile = true

[[files]]
file = "mods/no-resource-pack-warnings.pw.toml"
hash = "d762a3e4156c8ce27be1fca0c8a1c095cfd29d321885eda24353a351ec1d9c80"
metafile = true

[[files]]
file = "mods/paper-doll.pw.toml"
hash = "7562a8487f83eed90685308731efc8ae8e4fc8e3b314d00a5ed92aef0f2b94af"
metafile = true

[[files]]
file = "mods/particle-effects.pw.toml"
hash = "c9d4c901eaa237d005c58b094108e93a07a5238916c855bc44a1565c5a0da62e"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "11d24c43e240249b5dd24e0dcdb99b4c3ada768c1cd1664ed18fc498d6add67c"
metafile = true

[[files]]
file = "mods/pickup-notifications.pw.toml"
hash = "98718a135893bf11095e9524d3572f8dbeadef29fecf0f8251247aaa99802f24"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "e674752dd4dd07c33d9b94f6e19c15ef893c356c3c5ed77aeaf35cf6d2325130"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "bedbd2675abf6bdb06c80570ba63d88e08caf7bb431d01e446d8770a5c62a9fb"
metafile = true

[[files]]
file = "mods/quickleafdecay.pw.toml"
hash = "53cf4b0c5b92e2cab1f9d30dedc4bb764f074ee7151be91b8f23cd763aa65cd9"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "ad2c2880cd91b5d927f3bfdba657189997cdd6dd30f46ee0d969a68de2bb2ad8"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "a2082dc982b6060bb48cbabb2f8177b73487ec10a8f3d409a0fe099ec4899157"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
hash = "655bc945df6491a4f22eea0429f10b20447e48488ba0794cb301bd6e7cc465dd"
metafile = true

[[files]]
file = "mods/scribble.pw.toml"
hash = "cb4cce65ff8a0cf0a88fe8cb3d321f94f9d7f6a27b0a20631c9352ec0a2778ba"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "5ae220cfbb26641c68740ad0166c78f353680886fc28087e63bf07280a47ddbb"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "886b70d966a36dca61cbd19c4d3955ed657206ce9b8491aad7894c0a369355cd"
metafile = true

[[files]]
file = "mods/servux.pw.toml"
hash = "40851322be130d051190af0a939c36799d676e94c1ae3e555eacefe1ff28648c"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "f3f30366b2d911291021d2003108e0bf26da22f3221a669800db6484e1e28c7f"
metafile = true

[[files]]
file = "mods/silk.pw.toml"
hash = "493a76add332abb0dfa23004300ea2ae77a8448960f603519c1db5ab4d769413"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "2d27a6e7c7e28a33b4e3d85106f80fd6629f060ec31a8be525f1c2ac9f769cf1"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "279ea1bb4b776be9176fe34416e2132e37abfce4483def54177091cc0f2faade"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "2520b331c2b0eb582b448c4ebf1a73d66d42184acc2d74912baef4140e05ee9b"
metafile = true

[[files]]
file = "mods/status-effect-bars.pw.toml"
hash = "9a0d53217201df1a02fd2c4db95b61136da9b94e734876fe63116f4811538ed5"
metafile = true

[[files]]
file = "mods/storage-delight.pw.toml"
hash = "d34f5cfed623efa4bbe69030948a7d6531f0aecca9a1db41330b2a522cbbede7"
metafile = true

[[files]]
file = "mods/storagedrawers.pw.toml"
hash = "eccf47ca447c4970ae7322612b3beab1138b4b510a365dd7f33373f4d33e03a0"
metafile = true

[[files]]
file = "mods/subtle-effects.pw.toml"
hash = "2f3972058c89914c3bee061f436d199fbe938474bd2618e4b0f8082eb2d635d8"
metafile = true

[[files]]
file = "mods/tax-free-levels.pw.toml"
hash = "c27e7f71905ae66fbe0bf5c2acd9b8a83d27006e2c016c8b38ef4073309fc603"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "e166f736d7d67c4dd98cac1b927f571c1cabb58e1b3824b399b100fc77f18e44"
metafile = true

[[files]]
file = "mods/text-formatting-everywhere.pw.toml"
hash = "7e08e4f76649a2fba00bb6eae7b59af18513c01140b50cd94299c70232c597c9"
metafile = true

[[files]]
file = "mods/travelersbackpack.pw.toml"
hash = "b2605e18f9c25905a92cd31c90d944d0f3a1262a2515bed0e8af95452b459284"
metafile = true

[[files]]
file = "mods/veinminer-enchantment.pw.toml"
hash = "79b8d7410138bbabb5795fe29c18f82fd9238e5fe000dfa4a0fbf77cd24011ae"
metafile = true

[[files]]
file = "mods/veinminer.pw.toml"
hash = "5cb9a93032a75644cdf442b05a29e0616c76df503ee6b3dd3ab367ad1a04ff60"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "e71ac6769675de1d2338a13e116f2aefcc8965ab0bc18b75a53572531c1447dd"
metafile = true
