name = "Vanilla Plus"
author = "Redacted"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ccb5f029be0572b232fd58432b13e45796e7f69bbdb66a6bc8318034371e5da8"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"
