name = "Vanilla Plus"
author = "Redacted"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9c8fbf90c7c135c1163e865ef11c34abbc8f2453656113388fc575d49b8d8c6"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"
