name = "Vanilla Plus Plus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f03f4abcdf8ccf6900d01e40055bd4bdd60659977aa5e0ab8eb99e1bdbd698a"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"
